import org.jetbrains.compose.desktop.application.dsl.TargetFormat

// The window over the desktop sessions, and nothing else.
//
// A module of its own rather than a source set in :desktop, because the two cannot share a
// classpath the application plugin assembles: Compose's runtime and AndroidX's each ship a jar
// named runtime-desktop-1.9.0.jar with different contents, and telling installDist to exclude the
// duplicate builds green and dies at launch on NoClassDefFoundError - it drops the one that was
// needed. So :desktop keeps installDist for the measuring tools and this one runs and packages
// the Compose way.
plugins {
    id("org.jetbrains.kotlin.jvm")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.compose")
}

kotlin {
    // For the same reason as :desktop - the sessions under this window call Windows through FFM.
    jvmToolchain(25)
}

// As in :desktop: Kotlin 2.2.10 emits at most 24, so Java is brought down to meet it.
tasks.withType<JavaCompile>().configureEach {
    options.release.set(24)
}

// The about block's facts, by the handset's rules (app/build.gradle.kts): the commit read out of
// .git, the version from the tag that started a release build, the rest from gradle.properties.
// Written as a Kotlin object because this module has no BuildConfig; an unset fact arrives empty
// and the window leaves its row out.
val buildMark: String = runCatching {
    val gitDir = rootProject.file(".git")
    val head = File(gitDir, "HEAD").readText().trim()
    if (head.startsWith("ref:")) File(gitDir, head.removePrefix("ref:").trim()).readText().trim().take(7)
    else head.take(7)
}.getOrDefault("unknown")
val released: String? =
    System.getenv("SOUNDMESH_VERSION")?.trim()?.removePrefix("v")?.takeIf { it.isNotBlank() }

val aboutFacts = tasks.register("aboutFacts") {
    val facts = linkedMapOf(
        "VERSION" to (released ?: "0.1.0"),
        "BUILD_MARK" to buildMark,
        "AUTHOR" to (project.findProperty("soundmesh.author") ?: ""),
        "AUTHOR_URL" to (project.findProperty("soundmesh.authorUrl") ?: ""),
        "REPO_URL" to (project.findProperty("soundmesh.repoUrl") ?: ""),
        "LICENCE" to (project.findProperty("soundmesh.licence") ?: "")
    ).mapValues { it.value.toString() }
    val out = layout.buildDirectory.dir("generated/about")
    inputs.properties(facts)
    outputs.dir(out)
    doLast {
        val file = out.get().file("com/soundmesh/desktop/app/About.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            "package com.soundmesh.desktop.app\n\n" +
                "/** Generated by :desktop-app's aboutFacts task. */\n" +
                "internal object About {\n" +
                facts.entries.joinToString("") { (name, value) -> "    const val $name = \"$value\"\n" } +
                "}\n"
        )
    }
}

// The window's words in both languages, read out of the handset's own string files rather than
// copied from them, so a wording changed there is changed here on the next build. What only a
// computer says lives beside them in the same format (src/main/words), each key prefixed pc_.
// Parsed with the handset's rules for the little its files use: a default that is Chinese, an
// English that falls back to it key by key, \' \" \n \\ and the five XML entities, and runs of
// whitespace outside quotes collapsed. A key in both sets fails the build, since one would
// silently win.
val phraseFiles = mapOf(
    "zh" to listOf(rootProject.file("app/src/main/res/values/strings.xml"), file("src/main/words/values/strings.xml")),
    "en" to listOf(rootProject.file("app/src/main/res/values-en/strings.xml"), file("src/main/words/values-en/strings.xml"))
)

fun readPhrases(files: List<File>): Map<String, String> {
    val found = linkedMapOf<String, String>()
    val entry = Regex("""<string\s+name="([^"]+)"[^>]*>([\s\S]*?)</string>""")
    for (source in files) for (match in entry.findAll(source.readText())) {
        val (name, raw) = match.destructured
        require(name !in found) { "$name is in more than one of $files" }
        var text = raw.trim()
        val quoted = text.length >= 2 && text.startsWith("\"") && text.endsWith("\"")
        text = if (quoted) text.substring(1, text.length - 1) else text.replace(Regex("""\s+"""), " ")
        text = text.replace("&lt;", "<").replace("&gt;", ">").replace("&quot;", "\"").replace("&apos;", "'").replace("&amp;", "&")
        text = Regex("""\\(.)""").replace(text) { if (it.groupValues[1] == "n") "\n" else it.groupValues[1] }
        found[name] = text
    }
    return found
}

val phrases = tasks.register("phrases") {
    val out = layout.buildDirectory.dir("generated/phrases")
    inputs.files(phraseFiles.values.flatten())
    outputs.dir(out)
    doLast {
        val zh = readPhrases(phraseFiles.getValue("zh"))
        val en = readPhrases(phraseFiles.getValue("en"))
        fun literal(text: String) = "\"" + text.replace("\\", "\\\\").replace("\"", "\\\"").replace("\$", "\\\$").replace("\n", "\\n") + "\""
        val file = out.get().file("com/soundmesh/desktop/app/Phrases.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            "package com.soundmesh.desktop.app\n\n" +
                "/** Generated by :desktop-app's phrases task from the handset's strings and src/main/words. */\n" +
                "@Suppress(\"ObjectPropertyName\", \"PropertyName\")\n" +
                "internal object Phrases {\n" +
                zh.entries.joinToString("") { (name, text) ->
                    "    val $name = Phrase(${literal(text)}, ${literal(en[name] ?: text)})\n"
                } +
                "\n    /** Every phrase by its key, for the test that holds the two languages to one shape. */\n" +
                "    val all: Map<String, Phrase> by lazy { mapOf(\n" +
                zh.keys.joinToString(",\n") { "        \"$it\" to $it" } +
                "\n    ) }\n" +
                "}\n"
        )
    }
}

kotlin.sourceSets.named("main") {
    kotlin.srcDir(aboutFacts)
    kotlin.srcDir(phrases)
    // The handset's look, from the same files the handset compiles (see app/build.gradle.kts).
    kotlin.srcDir(rootProject.file("ui-shared/src"))
}

dependencies {
    implementation(project(":desktop"))
    // :desktop depends on :core as implementation, so its types (DiscoveryFailure, used in
    // SinkStatus) do not reach this module's classpath without a direct dependency here too.
    implementation(project(":core"))
    implementation(compose.desktop.currentOs)
    // Not part of currentOs, unlike what its name suggests.
    implementation(compose.material3)
    testImplementation("junit:junit:4.13.2")
}

compose.desktop {
    application {
        mainClass = "com.soundmesh.desktop.app.MainKt"
        jvmArgs += listOf("--enable-native-access=ALL-UNNAMED")
        // Without this, run/package fork on whatever JDK Gradle itself is running on (JAVA_HOME,
        // here 17), not on the jvmToolchain(25) above - so pull the same toolchain JDK explicitly.
        // Looked for rather than required: this runs while the build is configured, and a machine
        // with only 17 - the handset release job, anybody building just the APK - has to get past
        // it. Without 25, compiling :desktop is what fails, and only when something asks for it.
        runCatching {
            javaToolchains.launcherFor { languageVersion.set(JavaLanguageVersion.of(25)) }.get().metadata.installationPath.asFile.absolutePath
        }.getOrNull()?.let { javaHome = it }
        nativeDistributions {
            packageName = "SoundMesh"
            // The exe's file version, from the same tag as the about block's.
            packageVersion = released ?: "1.0.0"
            modules("java.instrument", "jdk.unsupported")
            // The installer, beside the zipped folder createDistributable makes. packageMsi builds
            // it; the release workflow publishes both.
            targetFormats(TargetFormat.Msi)
            // The exe's own icon, what Explorer and a pinned taskbar button show before a window
            // exists. Made by tools/windows-icons.ps1, as are the windows' own in resources/icon.
            windows {
                iconFile.set(rootProject.file("asset/windows/SoundMesh.ico"))
                // Never to change: it is how Windows knows a new MSI is the same program and
                // replaces the old install rather than adding a second one beside it.
                upgradeUuid = "d3db8c31-d17f-4588-9587-acc610e13f18"
                menuGroup = "SoundMesh"
                shortcut = true
                // Per user: installs without asking for administrator rights, into the user's own
                // AppData, the same place the settings already live.
                perUserInstall = true
            }
        }
    }
}
