// The window over the desktop sessions, and nothing else.
//
// A module of its own rather than a source set in :desktop, because the two cannot share a
// classpath the application plugin assembles: Compose's runtime and AndroidX's each ship a jar
// named runtime-desktop-1.9.0.jar with different contents, and telling installDist to exclude the
// duplicate builds green and dies at launch on NoClassDefFoundError - it drops the one that was
// needed. So :desktop keeps installDist for the measuring tools and this one runs and packages
// the Compose way.
plugins {
    id("org.jetbrains.kotlin.jvm")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.compose")
}

kotlin {
    // For the same reason as :desktop - the sessions under this window call Windows through FFM.
    jvmToolchain(25)
}

// As in :desktop: Kotlin 2.2.10 emits at most 24, so Java is brought down to meet it.
tasks.withType<JavaCompile>().configureEach {
    options.release.set(24)
}

// The about block's facts, by the handset's rules (app/build.gradle.kts): the commit read out of
// .git, the version from the tag that started a release build, the rest from gradle.properties.
// Written as a Kotlin object because this module has no BuildConfig; an unset fact arrives empty
// and the window leaves its row out.
val buildMark: String = runCatching {
    val gitDir = rootProject.file(".git")
    val head = File(gitDir, "HEAD").readText().trim()
    if (head.startsWith("ref:")) File(gitDir, head.removePrefix("ref:").trim()).readText().trim().take(7)
    else head.take(7)
}.getOrDefault("unknown")
val released: String? =
    System.getenv("SOUNDMESH_VERSION")?.trim()?.removePrefix("v")?.takeIf { it.isNotBlank() }

val aboutFacts = tasks.register("aboutFacts") {
    val facts = linkedMapOf(
        "VERSION" to (released ?: "0.1.0"),
        "BUILD_MARK" to buildMark,
        "AUTHOR" to (project.findProperty("soundmesh.author") ?: ""),
        "AUTHOR_URL" to (project.findProperty("soundmesh.authorUrl") ?: ""),
        "REPO_URL" to (project.findProperty("soundmesh.repoUrl") ?: ""),
        "LICENCE" to (project.findProperty("soundmesh.licence") ?: "")
    ).mapValues { it.value.toString() }
    val out = layout.buildDirectory.dir("generated/about")
    inputs.properties(facts)
    outputs.dir(out)
    doLast {
        val file = out.get().file("com/soundmesh/desktop/app/About.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            "package com.soundmesh.desktop.app\n\n" +
                "/** Generated by :desktop-app's aboutFacts task. */\n" +
                "internal object About {\n" +
                facts.entries.joinToString("") { (name, value) -> "    const val $name = \"$value\"\n" } +
                "}\n"
        )
    }
}

kotlin.sourceSets.named("main") { kotlin.srcDir(aboutFacts) }

dependencies {
    implementation(project(":desktop"))
    // :desktop depends on :core as implementation, so its types (DiscoveryFailure, used in
    // SinkStatus) do not reach this module's classpath without a direct dependency here too.
    implementation(project(":core"))
    implementation(compose.desktop.currentOs)
    // Not part of currentOs, unlike what its name suggests.
    implementation(compose.material3)
}

compose.desktop {
    application {
        mainClass = "com.soundmesh.desktop.app.MainKt"
        jvmArgs += listOf("--enable-native-access=ALL-UNNAMED")
        // Without this, run/package fork on whatever JDK Gradle itself is running on (JAVA_HOME,
        // here 17), not on the jvmToolchain(25) above - so pull the same toolchain JDK explicitly.
        javaHome = javaToolchains.launcherFor { languageVersion.set(JavaLanguageVersion.of(25)) }.get().metadata.installationPath.asFile.absolutePath
        nativeDistributions {
            packageName = "SoundMesh"
            packageVersion = "1.0.0"
            modules("java.instrument", "jdk.unsupported")
        }
    }
}
